server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/api/user/**

        - id: product-service
          uri: http://product-service:8083
          predicates:
            - Path=/api/products/**

        - id: cart-service
          uri: http://cart-service:8084
          predicates:
            - Path=/api/cart/**

        - id: order-service
          uri: http://order-service:8085
          predicates:
            - Path=/api/orders/**

        - id: payment-service
          uri: http://payment-service:8086
          predicates:
            - Path=/api/payments/**
